### ISSUE TITLE
Unable to claim SDL rewards in sUSD metapool V2

### ISSUE THREAD

**Issue by zimh** [saddle-finance/saddle-contract#535]
![image](https://user-images.githubusercontent.com/19593719/157505615-3798c027-64f1-4c88-8ec8-008bf2e7f607.png)

1 - I was in two pools with my wallet 0xD90d5C7a6ebB19B45959CD622367E4Be0985a05C. sUSD Metapool 2 and tBTC metapool v2.

2 - I unstaked and withdrew my tokens from the sUSD Metapool v2.

[Ethereum Transaction Hash (Txhash) Details | Etherscan](https://etherscan.io/tx/0xd578b33b2d557247cd50723119d5f27f2199d333e87a9505101dad4610776824)
[Ethereum Transaction Hash (Txhash) Details | Etherscan](https://etherscan.io/tx/0x4296b8139e972af904d78d08de3500017f668ea33db08efed59dc1e394b0422b)
3 - I clicked "claim all" to get my SDL to claim my SDL from both pools

4 - Two transactions popped up on metamask and completed, although both show errors:

[Ethereum Transaction Hash (Txhash) Details | Etherscan](https://etherscan.io/tx/0x80eb037584af85640f1396f88201bc48e6696eaca459857b8b9c9d20d13f924c)
[Ethereum Transaction Hash (Txhash) Details | Etherscan](https://etherscan.io/tx/0x334eaffd857546cbcb678c6a97b97a17ff7b3d58f40e732bba8f487c6ba7d566)
5 - It claimed my SDL from the tBTC pool.

6 - It did not claim my SDL from the sUSD pool. My SDL is still in that pool.

7 - When I click on 'claim' to try to get my SDL from the sUSD pool, I get an error on the Saddle.finance website: "your transaction has failed. unable to claim reward". 

8 - Tried disconnecting and reconnecting (using a Trezor), and a refresh of the website, etc. and tried again and getting this error:

```MetaMask - RPC Error: execution reverted: BoringERC20: Transfer failed {code: -32603, message: 'execution reverted: BoringERC20: Transfer failed', data: {…}}
(anonymous) @ inpage.js:1
(anonymous) @ inpage.js:17
_runReturnHandlers @ inpage.js:17
_processRequest @ inpage.js:17
await in _processRequest (async)
_handle @ inpage.js:17
handle @ inpage.js:17
_rpcRequest @ inpage.js:1
(anonymous) @ inpage.js:1
request @ inpage.js:1
(anonymous) @ web3-provider.ts:96
value @ web3-provider.ts:169
(anonymous) @ json-rpc-provider.ts:560
l @ runtime.js:63
(anonymous) @ runtime.js:293
(anonymous) @ runtime.js:118
(anonymous) @ 4.9611b28d.chunk.js:2
k @ 4.9611b28d.chunk.js:2
value @ 4.9611b28d.chunk.js:2
(anonymous) @ base-provider.ts:1442
l @ runtime.js:63
(anonymous) @ runtime.js:293
(anonymous) @ runtime.js:118
a @ 4.9611b28d.chunk.js:2
Promise.then (async)
u @ 4.9611b28d.chunk.js:2
a @ 4.9611b28d.chunk.js:2
Promise.then (async)
u @ 4.9611b28d.chunk.js:2
(anonymous) @ 4.9611b28d.chunk.js:2
E @ 4.9611b28d.chunk.js:2
value @ 4.9611b28d.chunk.js:2
value @ json-rpc-provider.ts:183
value @ json-rpc-provider.ts:288
(anonymous) @ index.ts:424
l @ runtime.js:63
(anonymous) @ runtime.js:293
(anonymous) @ runtime.js:118
a @ 4.9611b28d.chunk.js:2
Promise.then (async)
u @ 4.9611b28d.chunk.js:2
(anonymous) @ 4.9611b28d.chunk.js:2
k @ 4.9611b28d.chunk.js:2
(anonymous) @ 4.9611b28d.chunk.js:2
(anonymous) @ TokenClaimDialog.tsx:277
l @ runtime.js:63
(anonymous) @ runtime.js:293
(anonymous) @ runtime.js:118
r @ asyncToGenerator.js:3
s @ asyncToGenerator.js:25
(anonymous) @ asyncToGenerator.js:32
(anonymous) @ asyncToGenerator.js:21
(anonymous) @ TokenClaimDialog.tsx:268
claimCallback @ TokenClaimDialog.tsx:170
Ve @ react-dom.production.min.js:52
Je @ react-dom.production.min.js:52
(anonymous) @ react-dom.production.min.js:53
_r @ react-dom.production.min.js:100
Er @ react-dom.production.min.js:101
(anonymous) @ react-dom.production.min.js:113
Le @ react-dom.production.min.js:292
(anonymous) @ react-dom.production.min.js:50
Tr @ react-dom.production.min.js:105
Qt @ react-dom.production.min.js:75
Zt @ react-dom.production.min.js:74
t.unstable_runWithPriority @ scheduler.production.min.js:18
Vi @ react-dom.production.min.js:122
Ne @ react-dom.production.min.js:292
Yt @ react-dom.production.min.js:73
r @ helpers.ts:88
instrument.ts:130

Error: cannot estimate gas; transaction may fail or may require manual gas limit (error={"code":-32603,"message":"execution reverted: BoringERC20: Transfer failed","data":{"originalError":{"code":3,"data":"0x08c379a00000000000000000000000000000000000000000000000000000000000000020000000000000000000000000000000000000000000000000000000000000001c426f72696e6745524332303a205472616e73666572206661696c656400000000","message":"execution reverted: BoringERC20: Transfer failed"}}}, method="estimateGas", transaction={"from":"0xD90d5C7a6ebB19B45959CD622367E4Be0985a05C","to":"0x691ef79e40d909C715BE5e9e93738B3fF7D58534","data":"0x18fccc760000000000000000000000000000000000000000000000000000000000000006000000000000000000000000d90d5c7a6ebb19b45959cd622367e4be0985a05c","accessList":null}, code=UNPREDICTABLE_GAS_LIMIT, version=providers/5.5.2)
at e.value (index.ts:225:28)
at e.value (index.ts:237:20)
at E (json-rpc-provider.ts:80:16)
at n.<anonymous> (json-rpc-provider.ts:562:20)
at l (runtime.js:63:40)
at Generator._invoke (runtime.js:293:22)
at Generator.throw (runtime.js:118:21)
at s (4.9611b28d.chunk.js:2:294160)```

**Comment by zimh** [comment]
From user: 

> I was able to claim this morning! Not sure what changed (I did see a metamask update happen) - but it worked great and no issues now. Thanks for your help.
